Serialized the library
illumon-public/SuanShu pull request #1
Opened 2018-05-04 16:48 UTC by illumon-public

Testing of at least one class of each category has been done in the console.

2018-05-15 16:23 UTC, chipkent requested changes

2018-05-15 16:23 UTC, chipkent commented on build.gradle
>      baseName = 'SuanShuExtension'
Should be renamed 'SuanShu'

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/triangle/UpperTriangularMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug.  If the object goes through a serialize/deserialize cycle, math  will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/DenseMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/sparse/CSRSparseMatrix.java
> +    private final transient MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/sparse/DOKSparseMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/sparse/LILSparseMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/GivensMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/operation/FastKroneckerProduct.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/operation/SubMatrixRef.java
> +    private transient final MatrixMathOperation matrixComputation = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, matrixComputation will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/number/doublearray/ParallelDoubleArrayOperation.java
> +    private static final ParallelExecutor parallel = new ParallelExecutor();
Can you explain this switch to static?  Could this be the source of the excessive threads?

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    public static void setConcurrencyLevel(final int concurrency) {
Setting the concurrency level after an executor is created does not reset the concurrency level.  Maybe this is ok.  It needs to be thought through.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    public static void setConcurrencyLevel(final int concurrency) {
If this is the desired behavior, it needs to be documented.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +        if (concurrency <= 0 || concurrency > Runtime.getRuntime().availableProcessors()) {
I think this case should just be for concurrency <=0.  There are cases when you want to run more threads than processors.  For example, consider cases that do a lot of IO.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/stats/random/concurrent/ConcurrentCachedGenerator.java
> +    private static final Object lock = new Object();
This static is suspicious.  This creates a single lock for all objects, while previously it was a separate lock per object.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/stats/stochasticprocess/multivariate/MultiVariateRealization.java
> +    public static abstract class Iterator implements java.util.Iterator<MultiVariateRealization.Entry>, Serializable {
This static is potentially suspicious.  Are you certain that no refrence to the parent class/object is needed in any subclasses?

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/stats/stochasticprocess/univariate/Realization.java
> +    public static abstract class Iterator implements java.util.Iterator<Realization.Entry>, Serializable {
Potentially suspicious change to static.  Are you certain that no refs to the parent object need to be maintained?

2018-05-15 16:23 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/general/sqp/activeset/equalityconstraint/SQPActiveSetSolverForOnlyEqualityConstraint1Test.java
> +        x = soln.search(new DenseVector(0.03, 0.015, 0.3), new DenseVector(-1., -1.));
Why was this changed by 10x?

2018-05-15 16:23 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryMixedCutTest.java
> -        assertArrayEquals(new double[]{2, 1}, soln.minimizer().toArray(), 0);
Why were these values transposed?

2018-05-15 16:23 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryPureCutTest.java
> -        assertArrayEquals(new double[]{2, 1}, soln.minimizer().toArray(), 0);
Why were these values transposed?

2018-05-15 16:23 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/PowellTest.java
> -        assertEquals(0.0, fxmin, 1e-8);
Why was this changed by 10^5?

2018-05-15 16:23 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
Assertion was removed!

2018-05-15 16:23 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
Assertion was removed!

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/diagonal/DiagonalDataMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/triangle/LowerTriangularMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 16:23 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/triangle/SymmetricMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
I suspect this transient change is a bug. If the object goes through a serialize/deserialize cycle, math will be null, which seems to break the initial non-null final value.

2018-05-15 19:01 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/stats/random/concurrent/ConcurrentCachedGenerator.java
> +    private static final Object lock = new Object();
The Object class is not serialized. I made it static because it is private and we are not publishing the reference via any getters.

2018-05-15 19:05 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/triangle/UpperTriangularMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:05 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/DenseMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:05 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/sparse/CSRSparseMatrix.java
> +    private final transient MatrixMathOperation math = new SimpleMatrixMathOperation();
Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:07 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/sparse/DOKSparseMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:07 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/sparse/LILSparseMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:08 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/GivensMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:08 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/operation/FastKroneckerProduct.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:08 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/operation/SubMatrixRef.java
> +    private transient final MatrixMathOperation matrixComputation = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:16 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/number/doublearray/ParallelDoubleArrayOperation.java
> +    private static final ParallelExecutor parallel = new ParallelExecutor();
Naman: I made it static so that it won't get serialized as ParallelExecutor class is not serializable. The excessive threading thing is happening in the different branch where this variable is not static. I think if I have to make it non-static then I need to make it transient and initialize it in readObject() method (and for that I need to make it non-final)

2018-05-15 19:19 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    public static void setConcurrencyLevel(final int concurrency) {
Naman: While designing, I thought the usage of this as: first, the user has to define concurrency and then he has to create the object.

2018-05-15 19:19 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +        if (concurrency <= 0 || concurrency > Runtime.getRuntime().availableProcessors()) {
Naman: just one condition (<=0)

2018-05-15 19:25 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/general/sqp/activeset/equalityconstraint/SQPActiveSetSolverForOnlyEqualityConstraint1Test.java
> +        x = soln.search(new DenseVector(0.03, 0.015, 0.3), new DenseVector(-1., -1.));
Naman: I think I mistakenly committed this change to this branch instead of other. The testcase was failing for the earlier value.

2018-05-15 19:25 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryMixedCutTest.java
> -        assertArrayEquals(new double[]{2, 1}, soln.minimizer().toArray(), 0);
Naman: I think I mistakenly committed this change to this branch instead of other. The testcase was failing for the earlier value.

2018-05-15 19:25 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryPureCutTest.java
> -        assertArrayEquals(new double[]{2, 1}, soln.minimizer().toArray(), 0);
Naman: I think I mistakenly committed this change to this branch instead of other. The testcase was failing for the earlier value.

2018-05-15 19:28 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/triangle/SymmetricMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:28 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/triangle/LowerTriangularMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:28 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/diagonal/DiagonalDataMatrix.java
> +    private transient final MatrixMathOperation math = new SimpleMatrixMathOperation();
Naman: Made SimpleMatrixMathOperation implement Serializable and removed the transient keyword.

2018-05-15 19:32 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/PowellTest.java
> -        assertEquals(0.0, fxmin, 1e-8);
Naman: I think I mistakenly committed this change to this branch instead of other. The testcase was failing for the earlier value.

2018-05-15 19:32 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
Naman: I think I mistakenly committed this change to this branch instead of other. The testcase was failing for the earlier value.

2018-05-15 19:33 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
Naman: I think I mistakenly committed this change to this branch instead of other. The testcase was failing for the earlier value.

2018-05-15 20:28 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/stats/stochasticprocess/multivariate/MultiVariateRealization.java
> +    public static abstract class Iterator implements java.util.Iterator<MultiVariateRealization.Entry>, Serializable {
Naman: So according to my research, inner classes of an interface are by default public and static. IntelliJ is saying that "public static" keywords are redundant for Iterator class.

2018-05-15 20:28 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/stats/stochasticprocess/univariate/Realization.java
> +    public static abstract class Iterator implements java.util.Iterator<Realization.Entry>, Serializable {
Naman: So according to my research, inner classes of an interface are by default public and static. IntelliJ is saying that "public static" keywords are redundant for Iterator class.

2018-05-18 16:18 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/stats/random/concurrent/ConcurrentCachedGenerator.java
> +    private static final Object lock = new Object();
Making it static completely changes the locking behavior.  Now all instances have contention on the same lock.

2018-05-18 21:33 UTC, illumon-public commented on build.gradle
>      baseName = 'SuanShuExtension'
Made it 'SuanShu'

2018-05-21 16:17 UTC, chipkent requested changes
Comments have still not beenen addressed.

2018-05-21 16:17 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +public class ParallelMatrixMathOperation implements MatrixMathOperation {
It is still not clear to me that this should be public.

2018-05-21 16:17 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/number/doublearray/ParallelDoubleArrayOperation.java
> +    private static final ParallelExecutor parallel = new ParallelExecutor();
Looks like the executor has not been addressed yet.

2018-05-21 16:17 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
>      public ParallelExecutor(int concurrency) {
ParallelExecutor changes have not been implemented.

2018-05-21 16:17 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/vector/doubles/dense/DenseVector.java
> +    private transient VectorMathOperation math = new VectorMathOperation();
transient bug

2018-05-21 16:17 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryMixedCutTest.java
> -        assertArrayEquals(new double[]{2, 1}, soln.minimizer().toArray(), 0);
Still concerned with the transpose.  How certain are you that the code is. behaving properly?

2018-05-21 16:17 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryPureCutTest.java
> -        assertArrayEquals(new double[]{2, 1}, soln.minimizer().toArray(), 0);
Still concerned with the transpose. How certain are you that the code is. behaving properly?

2018-05-21 16:17 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/PowellTest.java
> -        assertEquals(0.0, fxmin, 1e-8);
I'm concerned about the large change.  If the change should not be here, revert it.

2018-05-21 16:17 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
The assertion is still missing.  If the change should not be here, it should be removed.

2018-05-21 16:17 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
The assertion is still missing.  If the change should not be here, it should be removed.

2018-05-21 16:22 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +public class ParallelMatrixMathOperation implements MatrixMathOperation {
I read through the code.  Public is fine... but I don't see any way that a user could even use this.  All MatrixMathOperation instances I see are private final and set to the serial version.

2018-05-21 16:26 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +public class ParallelMatrixMathOperation implements MatrixMathOperation {
Additionally, the parallelmatrixmathoperation is not serializable and does not have updated executor code.

2018-05-21 17:28 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/vector/doubles/dense/DenseVector.java
> +    private transient VectorMathOperation math = new VectorMathOperation();
Removed transient and made VectorMathOperation implement Serializable

2018-05-21 17:34 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
Fixed in the other branch.

2018-05-21 17:38 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +public class ParallelMatrixMathOperation implements MatrixMathOperation {
Made non-public.

2018-05-21 20:44 UTC, chipkent requested changes

2018-05-21 20:44 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/DenseMatrix.java
> +        private static final ParallelExecutor instance = ParallelExecutor.getInstance();
The ParallelExecutorInstanceHolder shoul d be removed, and ParallelExecutorInstanceHolder.instance should be replaced by ParallelExecutor.getInstance()

2018-05-21 20:44 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +    private final ParallelExecutor parallel = ParallelExecutor.getInstance();
parallel variable should be replaced by  calls to ParallelExecutor.getInstance()

2018-05-21 20:44 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/number/doublearray/ParallelDoubleArrayOperation.java
> +    private transient ParallelExecutor parallel = ParallelExecutor.getInstance();
Replace the paralllel variable with calls to ParallelExecutor.getInstance(), and you can remove the transient and transient handling.

2018-05-21 20:44 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/optimization/geneticalgorithm/GeneticAlgorithm.java
> +        this.parallel = parallel ? ParallelExecutor.getInstance() : null;
I would restructure this.  I would make parallel a boolean and would replace calls to the executor with ParallelEecutor.gitInstance()

2018-05-21 20:44 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/parallel/ParallelExecutorTest.java
> +        ParallelExecutor.setConcurrencyLevel(2);
These concurrency changes pollute other tests.  There should be a shutdown method that resets the executor to the desired number of threads.

2018-05-21 20:44 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/stats/random/concurrent/ConcurrentCachedGeneratorTest.java
> +        ParallelExecutor parallelExecutor = ParallelExecutor.getInstance();
Combine these two lines into one.

2018-05-21 20:44 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/stats/random/concurrent/ConcurrentCachedRNGTest.java
> +        ParallelExecutor.setConcurrencyLevel(nLoops);
shutdown method should reset the concurrency level.

2018-05-21 20:44 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    private static int concurrency = 1;
concurrency should be a private final variable.

2018-05-21 20:44 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    public static synchronized void setConcurrencyLevel(final int concurrency) {
private static ParallelExecutor parallelExecutor;
//todo not needed —> private static boolean concurrencyChanged = false;

//todo not needed
/**
 * Creates an instance using default concurrency number, which is the
 * number of available processors returned by
 * <pre><code>
 * Runtime.getRuntime().availableProcessors()
 * </code></pre>
 */
//private ParallelExecutor() {
//    this(concurrency);
//}


public static synchronized ParallelExecutor getInstance() {
//todo not needed
//    if (parallelExecutor == null || concurrencyChanged) {
//        parallelExecutor = new ParallelExecutor(concurrency);
//        concurrencyChanged = false;
//    }
    return parallelExecutor;
}

/**
 * Sets the concurrency level for the ParallelExecutor.
 *
 * @param concurrency concurrency level to set
 */
public static synchronized void setConcurrencyLevel(final int concurrency) {
//todo changed
final int realConcurrency = concurrency < 0 ? *** : concurrency;
if( realConcurrency != parallelExecutor.concurrency {
parallelExecutor = new ParallelExecutor(realConcurrency);
}
//    if (concurrency != ParallelExecutor.concurrency) {
//        ParallelExecutor.concurrency = concurrency;
//        concurrencyChanged = true;
//    }
}

2018-05-21 20:44 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +            concurrency = Runtime.getRuntime().availableProcessors();
Remove this block from the constructor and put it in the setter.

2018-05-21 22:36 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
>      public ParallelExecutor(int concurrency) {
Implemented.

2018-05-21 22:37 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/dense/DenseMatrix.java
> +        private static final ParallelExecutor instance = ParallelExecutor.getInstance();
Removed

2018-05-21 22:38 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +    private final ParallelExecutor parallel = ParallelExecutor.getInstance();
Replaced.

2018-05-21 22:38 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/number/doublearray/ParallelDoubleArrayOperation.java
> +    private transient ParallelExecutor parallel = ParallelExecutor.getInstance();
Done as suggested.

2018-05-21 22:38 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/optimization/geneticalgorithm/GeneticAlgorithm.java
> +        this.parallel = parallel ? ParallelExecutor.getInstance() : null;
Restructured.

2018-05-21 22:39 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/parallel/ParallelExecutorTest.java
> +        ParallelExecutor.setConcurrencyLevel(2);
Added shutdown() method that sets concurrency-level to 1.

2018-05-21 22:41 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/stats/random/concurrent/ConcurrentCachedGeneratorTest.java
> +        ParallelExecutor parallelExecutor = ParallelExecutor.getInstance();
Done.

2018-05-21 22:41 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/stats/random/concurrent/ConcurrentCachedRNGTest.java
> +        ParallelExecutor.setConcurrencyLevel(nLoops);
Added shutdown() method that sets concurrency-level to 1.

2018-05-21 22:42 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    public static synchronized void setConcurrencyLevel(final int concurrency) {
Done.

2018-05-21 22:42 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +            concurrency = Runtime.getRuntime().availableProcessors();
Removed.

2018-05-21 23:59 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    private static int concurrency = 1;
Done.

2018-05-22 05:02 UTC, merged