Solve testcases
illumon-public/SuanShu pull request #2
Opened 2018-05-15 15:24 UTC by illumon-public

Still working on the two arbitrarily failing testclasses
1. FactorAnalysisTest
2. com.numericalmethod.suanshu.stats.hmm.mixture.BetaDistributionTest

2018-05-15 16:50 UTC, chipkent requested changes

2018-05-15 16:50 UTC, chipkent commented on build.gradle
>      baseName = 'SuanShuExtension'
See comments in the other branch.  Change to SuanShu.

2018-05-15 16:50 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/analysis/function/polynomial/root/QuadraticRoot.java
> +        if (compare(e, 0, Constant.EPSILON) >= 0) {
I'm not certain that this change is correct.  This seems to be doing a root solver, where the root needs to be identically zero.  Can you explain this to me?

2018-05-15 16:50 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +public class ParallelMatrixMathOperation implements MatrixMathOperation {
Why does this need to be public?

2018-05-15 16:50 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    private static int concurrency = 1;
concurrency went from local final to static non-final.  This leads to some weird behavior.

2018-05-15 16:50 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +    private static int concurrency = 1;
I need to more carefully review the parallelization change.

2018-05-15 16:50 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +        ParallelExecutor.concurrency = concurrency;
This doesn't impact already running pools.  Maybe ok, but undocumented.

2018-05-15 16:50 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +        if (concurrency <= 0 || concurrency > Runtime.getRuntime().availableProcessors()) {
See my comment in the other branch.

2018-05-15 16:50 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
>          this.concurrency = concurrency;
It is weird that the constructor is setting a static variable this way.  The design needs work.

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperationTest.java
> +        if (ParallelExecutor.getConcurrencyLevel() > 1) {
What is the default concurrency level for tests?  Do we tests in multiple levels?

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/general/sqp/activeset/equalityconstraint/SQPActiveSetSolverForOnlyEqualityConstraint1Test.java
> +        x = soln.search(new DenseVector(0.03, 0.015, 0.3), new DenseVector(-1., -1.));
Value has changed by 10x.  Explain...

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryMixedCutTest.java
> +        assertArrayEquals(new double[]{1, 2}, soln.minimizer().toArray(), 0);
Transpose looks suspicious.

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryPureCutTest.java
> +        assertArrayEquals(new double[]{1, 2}, soln.minimizer().toArray(), 0);
Transpose looks suspicious.

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/PowellTest.java
> +        assertEquals(0.0, fxmin, 1e-3);
10^5 change looks suspicious.

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
assert commented out!

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
assert commented out!

2018-05-15 16:50 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/vector/doubles/dense/VectorMathOperationTest.java
> +    @Test
Other test cases use Junit3 and not Junit4 (at least that is what I've noticed).  If I am right, tests should be indicated with public void test_<stuff>(), rather than the @Test annotation.

2018-05-15 21:26 UTC, illumon-public commented on build.gradle
>      baseName = 'SuanShuExtension'
Made it 'SuanShu'.

2018-05-16 16:02 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperationTest.java
> +        if (ParallelExecutor.getConcurrencyLevel() > 1) {
I have tested with concurrencyLevel 1, 2, and 4.

2018-05-17 17:46 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/analysis/function/polynomial/root/QuadraticRoot.java
> +        if (compare(e, 0, Constant.EPSILON) >= 0) {
Constant.EPSILON is the smallest difference between two doubles. If two doubles are less than epsilon, then they are same.

2018-05-17 17:47 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +public class ParallelMatrixMathOperation implements MatrixMathOperation {
I made it public for a use-case where a user wants to use it outside of the package for custom computation?

2018-05-17 17:51 UTC, illumon-public commented on src/main/java/com/numericalmethod/suanshu/parallel/ParallelExecutor.java
> +        if (concurrency <= 0 || concurrency > Runtime.getRuntime().availableProcessors()) {
Fixed on the other branch.

2018-05-17 19:24 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/general/sqp/activeset/equalityconstraint/SQPActiveSetSolverForOnlyEqualityConstraint1Test.java
> +        x = soln.search(new DenseVector(0.03, 0.015, 0.3), new DenseVector(-1., -1.));
For the earlier value (0.003), the assertions fail. IIRC, I got to this value using trial and error.

2018-05-17 19:49 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryMixedCutTest.java
> +        assertArrayEquals(new double[]{1, 2}, soln.minimizer().toArray(), 0);
soln has two minimizers, {1, 2} and {2, 1} on indexes 0 and 1 respectively. The soln.minimizer() is coded to return first element, hence we're getting {1, 2}. It might be the case that when they created the test case, it was on 0th index.

2018-05-17 19:50 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/constrained/integer/linear/cuttingplane/GomoryPureCutTest.java
> +        assertArrayEquals(new double[]{1, 2}, soln.minimizer().toArray(), 0);
soln has two minimizers, {1, 2} and {2, 1} on indexes 0 and 1 respectively. The soln.minimizer() is coded to return first element, hence we're getting {1, 2}. It might be the case that when they created the test case, it was on 0th index.

2018-05-17 20:00 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/PowellTest.java
> +        assertEquals(0.0, fxmin, 1e-3);
fxmin=1.7648471578453193E-4, and fails for finer epsilons.

2018-05-17 20:34 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
Interestingly, when epsilon2 (2nd argument of Zangwill constructor is big (like 1), according to the javadocs, epsilon2 is "a precision parameter to decide whether there is a linear dependence among the conjugate directions"), It performs better and all testcases pass with little less precision (passes assertEquals(0.0, fxmin, 1e-4))

2018-05-17 20:34 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/optimization/unconstrained/conjugatedirection/ZangwillTest.java
> +//        assertEquals(0.0, fxmin, 1e-2);
Interestingly, when epsilon2 (2nd argument of Zangwill constructor is big (like 1), according to the javadocs, epsilon2 is "a precision parameter to decide whether there is a linear dependence among the conjugate directions"), It performs better and all testcases pass with little less precision (passes assertEquals(0.0, fxmin, 1e-4))

2018-05-17 20:42 UTC, illumon-public commented on src/test/java/com/numericalmethod/suanshu/vector/doubles/dense/VectorMathOperationTest.java
> +    @Test
The raw Suanshu code uses @Test annotation and annotations were introduced in junit4.

2018-05-18 16:21 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/analysis/function/polynomial/root/QuadraticRoot.java
> +        if (compare(e, 0, Constant.EPSILON) >= 0) {
Can you guarantee that this change is correct?  Could there be a situation where this comparison is |a-b|<=eps, where the equality could happen for non-identical cases?

2018-05-18 16:22 UTC, chipkent commented on src/main/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperation.java
> +public class ParallelMatrixMathOperation implements MatrixMathOperation {
What exactly would that use case be?  The original authors and users never needed it to be public?

2018-05-18 16:23 UTC, chipkent commented on src/test/java/com/numericalmethod/suanshu/matrix/doubles/matrixtype/mathoperation/ParallelMatrixMathOperationTest.java
> +        if (ParallelExecutor.getConcurrencyLevel() > 1) {
Are these levels part of every run?

2018-05-22 05:42 UTC, merged